### PR TITLE
Unify the folder name

### PR DESCRIPTION
**Pull request by Doppon**
## Github Issues

https://github.com/TheAlgorithms/Ruby/issues/61

### CODE REVIEW

**Comment by vzvu3k6k** [comment]
Looks good.

How about renaming `Searches` to `searches` and `Sorting` to `sorting` as #63 does?

**Comment by Doppon** [comment]
Thanks for your review and great suggestion
I lost the point when I changed.

Can you merge the branch？

**Comment by vzvu3k6k** [comment]
> Can you merge the branch？

Sure!

**Comment by vzvu3k6k** [comment]
@Doppon Thanks. I've just merged the branch.

**Review by vzvu3k6k — APPROVED** [review]

**Comment by Doppon** [comment]
Thanks for your help :)

**Pull request merged**
