### PR TITLE
3n plus 1 feature implementation

### PR DESCRIPTION
**Pull request by msaf9**
PR for 3n plus 1 feature

### CODE REVIEW

**Review by jsca-kwok — APPROVED** [review]

**Comment by msaf9** [comment]
Ohms law implementation PR

**Comment by jsca-kwok** [comment]
> Ohms law implementation PR

Nice addition! But maybe this should be in a separate PR from your 3n+1 PR?

**Comment by msaf9** [comment]
Yeah, I believe messed up in the same PR.

**Review by imvitoroliveira — APPROVED** [review]
LGTM

**Pull request merged**
