### PR TITLE
Added the solution for Problem 3

### PR DESCRIPTION
**Pull request by RitamDey**

### CODE REVIEW

**Comment by AnupKumarPanwar** [comment]
Hi @RitamDey . Please rename the file to follow the pattern used in other directories.

**Comment by RitamDey** [comment]
Okay will do!!

**Comment by vbrazo** [comment]
@RitamDey I've merged your other PR which contained the solution for the Problem 3 + 4. I was able to fix the pattern used in other directories that Anup asked you. Closing this since these changes are not necessary anymore.

**Comment by RitamDey** [comment]
@vbrazo thanks!! I completely forgot about this PR until now

**Pull request closed without merging**
